[tool.poetry]
name = "graphql-core-promise"
version = "3.2.3-1"
description = "Add support for promise-based dataloaders and resolvers to graphql-core v3+"
authors = ["Shen Li <dustet@gmail.com>"]
license = "MIT"
packages = [{include = "graphql_core_promise"}]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
pytest = "^7.1.3"
pytest-describe = "^2.0.1"

# These two are peer dependencies
graphql-core = "^3.2"
promise = "^2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
